matrix:
  include:
    - os: linux
      dist: trusty
      #sudo: required
      install:
        - mkdir swift
        - curl https://swift.org/builds/swift-4.2.1-release/ubuntu1404/swift-4.2.1-RELEASE/swift-4.2.1-RELEASE-ubuntu14.04.tar.gz -s | tar xz -C swift &> /dev/null
        - export PATH="$(pwd)/swift/swift-4.2.1-RELEASE-ubuntu14.04/usr/bin:$PATH"
      script:
        - swift package update
        - swift test
    - os: osx
      language: objective-c
      osx_image: xcode10.1
      before_install:
        - gem install cocoapods --pre
      script:
        - swift package update
        - swift test
        - pod lib lint 
